"""Pydantic response shapes for every swarm the engine calls.

One model per swarm output.  These are the JSON schemas we expect back
from each externally configured DAF swarm; the validators in
``validators.py`` (Step 0.5) check that responses conform.

See plan §11.2 for the swarm catalogue.
"""

from __future__ import annotations

from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

# Strict mode: reject unknown keys so prompt-leak / schema-drift fails loudly.
_BASE_MODEL_CONFIG = ConfigDict(extra="forbid", frozen=False)


# ---------------------------------------------------------------------------
# S1 IOI Tagger
# ---------------------------------------------------------------------------


class TaggerResponse(BaseModel):
    """Output of the S1 IOI Tagger agent.

    All eight tag fields are optional strings — the Tagger may extract
    a subset.  Per-field confidence is optional (the agent may or may
    not be configured to return it; if absent we treat as 1.0).
    """

    model_config = _BASE_MODEL_CONFIG

    side: str | None = None
    product: str | None = None
    qty: str | None = None
    tenor: str | None = None
    price: str | None = None
    qualifier: str | None = None
    urgency: str | None = None
    sentiment: str | None = None
    confidence: dict[str, float] = Field(default_factory=dict, description="Per-field confidence (0.0-1.0).")


# ---------------------------------------------------------------------------
# S2 Entity Profiler
# ---------------------------------------------------------------------------


class ProfilerResponse(BaseModel):
    """Output of the S2 Profiler swarm.  Fields mirror the persisted
    `entity_dossiers` content columns (plan §8.2).  `embedding` (vector)
    is intentionally absent — pgvector deferred for v1."""

    model_config = _BASE_MODEL_CONFIG

    archetype: str
    current_posture: str
    motive_priors: dict[str, Any] = Field(default_factory=dict)
    friction_notes: str = ""
    recent_activity: str = ""
    embedding_text: str = Field(
        ...,
        description="200-word version intended for future embedding (pgvector deferred per plan §17).",
    )


# ---------------------------------------------------------------------------
# S3 Market Reader
# ---------------------------------------------------------------------------


class MarketReaderResponse(BaseModel):
    """Output of the S3 Market Reader swarm.  Fields mirror the
    persisted `market_briefings` content columns (plan §8.3)."""

    model_config = _BASE_MODEL_CONFIG

    regime_label: str
    recent_move_summary: str
    liquidity_assessment: str
    broker_book_posture: str


# ---------------------------------------------------------------------------
# S4 Recommender Explainer
# ---------------------------------------------------------------------------


class RecommendationRationale(BaseModel):
    """Per-candidate rationale generated by the S4 swarm."""

    model_config = _BASE_MODEL_CONFIG

    entity_id: UUID
    ui_friendly_reasoning: str = Field(
        ...,
        description="Concise 5-30 word summary suitable for a list view.",
    )
    detailed_reasoning: str = Field(
        ...,
        description="One paragraph; explains the deterministic ranking rationale grounded in packet facts.",
    )


class RecommenderExplainerResponse(BaseModel):
    """Output of the S4 Recommender Explainer swarm: per-candidate
    rationales plus an originator-side hypothesis ('why this client is
    asking now')."""

    model_config = _BASE_MODEL_CONFIG

    candidates: list[RecommendationRationale]
    originator_hypothesis: str = Field(
        default="",
        description="1-2 sentence hypothesis on what's driving the originator's intent.",
    )


# ---------------------------------------------------------------------------
# S5 Match Strategist
# ---------------------------------------------------------------------------


class MatchStrategistResponse(BaseModel):
    """Output of the S5 Match Strategist swarm: a structured negotiation
    script for a confirmed match pair (plan §11.2)."""

    model_config = _BASE_MODEL_CONFIG

    who_to_call_first: str = Field(
        ...,
        description="Either 'buyer' / 'seller' / a specific entity_id or entity_name.",
    )
    pitch_to_buyer: str
    pitch_to_seller: str
    risk_flags: list[str] = Field(default_factory=list)
    residual_handling: str | None = None
    brokerage_economic_note: str | None = Field(
        default=None,
        description="Optional commentary on how this match interacts with the firm's exposure (soft signal only).",
    )


# ---------------------------------------------------------------------------
# S6 Coverage Coach
# ---------------------------------------------------------------------------


class CoverageCoachResponse(BaseModel):
    """Output of the S6 Coverage Coach swarm: a short outreach script
    the broker can edit."""

    model_config = _BASE_MODEL_CONFIG

    script: str
    suggested_subject: str | None = Field(
        default=None,
        description="Email subject line; null for non-email channels.",
    )
    channel_hint: str | None = Field(
        default=None,
        description="One of 'voice' | 'email' | 'chat' | None.",
    )


# ---------------------------------------------------------------------------
# Instrument Resolver (single agent, not a swarm — used by Step 0.10 seeding)
# ---------------------------------------------------------------------------


class InstrumentResolutionResponse(BaseModel):
    """Output of the Instrument Product Resolver agent (plan Step 0.10).

    Maps one free-text ``trade_history.instrument_name`` (plus optional
    CME-style ``symbol``) to the canonical product / structure / front
    contract month. Fields mirror ``instrument_products`` columns one-to-one;
    ``expiry_date`` is always returned as null per the agent's system
    instructions (out-of-scope for v1).
    """

    model_config = _BASE_MODEL_CONFIG

    product_name: str | None = Field(
        default=None,
        description="One of the canonical product names, or null when unresolvable.",
    )
    product_family: str | None = Field(
        default=None,
        description="Crude / Distillates / Refined / Nat Gas, or null.",
    )
    structure_type: str | None = Field(
        default=None,
        description="Outright | Spread | Butterfly | Crack | Swap | Strip | Unknown",
    )
    contract_month: str | None = Field(
        default=None,
        description="YYYY-MM front-leg month; null for strips / month-less names.",
    )
    expiry_date: str | None = Field(
        default=None,
        description="Always null in v1 — exact CME expiry rules are out of scope.",
    )
    confidence: float = Field(
        ...,
        description="0.0-1.0 confidence; values <0.3 mean the agent declined to guess.",
    )
    reasoning: str = Field(
        default="",
        description="One to three short sentences citing the substring(s) of the input.",
    )
